name: lint

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - main

jobs:
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DavidAnson/markdownlint-cli2-action@v7
      with:
        globs: "**/*.md"

  yaml-lint:
    name: yaml-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ibiqlik/action-yamllint@v3

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - name: Install golangci-lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.42.0
    - name: Run golangci-lint
      run: |
        $GITHUB_WORKSPACE/golangci-lint run --out-format=github-actions
